
version: '2'
services:

          mysql:
              build: .
              image: sockyjam/mysql.hive:v01
              container_name: socky.mysql.hive
              environment:
                  MYSQL_ROOT_PASSWORD: hive_mysql_Jfslw753lfaqp092L
                  MYSQL_DATABASE: db_hive
              volumes:
                  - ./dbdata:/var/lib/mysql
              ports:
                  - "3307:3306"
              expose:
                  - "3307"
                  - "3306"
              command:
                  --character-set-server=utf8
                  --collation-server=utf8_general_ci
